package tr.com.metamorfoz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClientRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("msisdn")
	private java.lang.String msisdn;
	@org.kie.api.definition.type.Label("imsi")
	private java.lang.String imsi;
	@org.kie.api.definition.type.Label("imei")
	private java.lang.String imei;
	@org.kie.api.definition.type.Label("iccid")
	private java.lang.String iccid;

	public ClientRequest() {
	}

	public java.lang.String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(java.lang.String msisdn) {
		this.msisdn = msisdn;
	}

	public java.lang.String getImsi() {
		return this.imsi;
	}

	public void setImsi(java.lang.String imsi) {
		this.imsi = imsi;
	}

	public java.lang.String getImei() {
		return this.imei;
	}

	public void setImei(java.lang.String imei) {
		this.imei = imei;
	}

	public java.lang.String getIccid() {
		return this.iccid;
	}

	public void setIccid(java.lang.String iccid) {
		this.iccid = iccid;
	}

	public ClientRequest(java.lang.String msisdn, java.lang.String imsi,
			java.lang.String imei, java.lang.String iccid) {
		this.msisdn = msisdn;
		this.imsi = imsi;
		this.imei = imei;
		this.iccid = iccid;
	}

}