package tr.com.metamorfoz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorCounter implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Error Count")
	private java.lang.Integer errorCount;
	@org.kie.api.definition.type.Label("Instance Id")
	private java.lang.Long instanceId;
	@org.kie.api.definition.type.Label("Last Error Timestamp")
	private java.util.Date lastErrorTimestamp;
	@org.kie.api.definition.type.Label("Node Instance Id")
	private java.lang.Long nodeInstanceId;

	public ErrorCounter() {
	}

	public java.lang.Integer getErrorCount() {
		return this.errorCount;
	}

	public void setErrorCount(java.lang.Integer errorCount) {
		this.errorCount = errorCount;
	}

	public java.lang.Long getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.Long instanceId) {
		this.instanceId = instanceId;
	}

	public java.util.Date getLastErrorTimestamp() {
		return this.lastErrorTimestamp;
	}

	public void setLastErrorTimestamp(java.util.Date lastErrorTimestamp) {
		this.lastErrorTimestamp = lastErrorTimestamp;
	}

	public java.lang.Long getNodeInstanceId() {
		return this.nodeInstanceId;
	}

	public void setNodeInstanceId(java.lang.Long nodeInstanceId) {
		this.nodeInstanceId = nodeInstanceId;
	}

	public ErrorCounter(java.lang.Integer errorCount,
			java.lang.Long instanceId, java.util.Date lastErrorTimestamp,
			java.lang.Long nodeInstanceId) {
		this.errorCount = errorCount;
		this.instanceId = instanceId;
		this.lastErrorTimestamp = lastErrorTimestamp;
		this.nodeInstanceId = nodeInstanceId;
	}

}