package tr.com.metamorfoz;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ErrorEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Error Message")
	private java.lang.String errorMessage;
	@org.kie.api.definition.type.Label("Instance Id")
	private java.lang.Long instanceId;
	@org.kie.api.definition.type.Label("Node Instance Id")
	private java.lang.Long nodeInstanceId;
	@org.kie.api.definition.type.Label("Timestamp")
	private java.util.Date timestamp;

	public ErrorEvent() {
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public java.lang.Long getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(java.lang.Long instanceId) {
		this.instanceId = instanceId;
	}

	public java.lang.Long getNodeInstanceId() {
		return this.nodeInstanceId;
	}

	public void setNodeInstanceId(java.lang.Long nodeInstanceId) {
		this.nodeInstanceId = nodeInstanceId;
	}

	public java.util.Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.util.Date timestamp) {
		this.timestamp = timestamp;
	}

	@Override
	public String toString() {
		return "ErrorEvent [errorMessage=" + errorMessage + ", instanceId="
				+ instanceId + ", nodeInstanceId=" + nodeInstanceId
				+ ", timestamp=" + timestamp + "]";
	}

	public ErrorEvent(java.lang.String errorMessage, java.lang.Long instanceId,
			java.lang.Long nodeInstanceId, java.util.Date timestamp) {
		this.errorMessage = errorMessage;
		this.instanceId = instanceId;
		this.nodeInstanceId = nodeInstanceId;
		this.timestamp = timestamp;
	}

}